/**
 * Event Types, Categories, and Status Enums for Worldview Disaster Intelligence.
 */

export const EventCategory = Object.freeze({
  HAZARD: 'HAZARD',
  OBSERVATION: 'OBSERVATION',
  ENVIRONMENTAL: 'ENVIRONMENTAL',
  MOVING_ENTITY: 'MOVING_ENTITY',
});

export const SourceMode = Object.freeze({
  LIVE: 'LIVE',
  SIMULATED: 'SIMULATED',
  FIXTURE: 'FIXTURE',
  DERIVED: 'DERIVED',
});

export const FreshnessStatus = Object.freeze({
  LIVE: 'LIVE',
  RECENT: 'RECENT',
  STALE: 'STALE',
  EXPIRED: 'EXPIRED',
  UNKNOWN: 'UNKNOWN',
});

export const EventType = Object.freeze({
  // Hazard Events
  EARTHQUAKE: 'EARTHQUAKE',
  TSUNAMI_SIGNAL: 'TSUNAMI_SIGNAL',
  WILDFIRE_HOTSPOT: 'WILDFIRE_HOTSPOT',
  FLOOD_SIGNAL: 'FLOOD_SIGNAL',
  CYCLONE: 'CYCLONE',
  OFFICIAL_WARNING: 'OFFICIAL_WARNING',
  HAZARD_TRACK: 'HAZARD_TRACK',

  // Environmental Observations
  WEATHER: 'WEATHER',
  METEOROLOGICAL_ANOMALY: 'METEOROLOGICAL_ANOMALY',
  LIGHTNING: 'LIGHTNING',

  // Moving Entities (Operational context)
  AIRCRAFT: 'AIRCRAFT',
  VESSEL: 'VESSEL',
  SATELLITE: 'SATELLITE',

  // Generic Sensor Observations & Baselines
  WATER_LEVEL_OBSERVATION: 'WATER_LEVEL_OBSERVATION',
  SEISMIC_STATION_READING: 'SEISMIC_STATION_READING',
  GENERIC_OBSERVATION: 'GENERIC_OBSERVATION',
  POPULATION_EXPOSURE: 'POPULATION_EXPOSURE',
  ELEVATION: 'ELEVATION',
});

export const IncidentStatus = Object.freeze({
  DETECTED: 'DETECTED',
  ASSESSING: 'ASSESSING',
  CONFIRMED: 'CONFIRMED',
  ACTIVE: 'ACTIVE',
  RESOLVED: 'RESOLVED',
  DISMISSED: 'DISMISSED',
});

export const SeverityLevel = Object.freeze({
  LOW: 'LOW',
  MODERATE: 'MODERATE',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});

export const EvidenceRelevance = Object.freeze({
  PRIMARY_HAZARD: 'PRIMARY_HAZARD',
  CORROBORATING_OBSERVATION: 'CORROBORATING_OBSERVATION',
  ENVIRONMENTAL_CONTEXT: 'ENVIRONMENTAL_CONTEXT',
  EXPOSURE_SIGNAL: 'EXPOSURE_SIGNAL',
  ANTECEDENT_CONDITION: 'ANTECEDENT_CONDITION',
  OFFICIAL_WARNING: 'OFFICIAL_WARNING',
});

export const CorroborationLevel = Object.freeze({
  CONFIRMED_BY_MULTIPLE_SOURCES: 'CONFIRMED_BY_MULTIPLE_SOURCES',
  SINGLE_SOURCE: 'SINGLE_SOURCE',
  CONFLICTING_SOURCES: 'CONFLICTING_SOURCES',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  UNKNOWN: 'UNKNOWN',
});

export const AnomalyType = Object.freeze({
  POINT_ANOMALY: 'POINT_ANOMALY',
  TIME_SERIES_ANOMALY: 'TIME_SERIES_ANOMALY',
  SPATIAL_CLUSTER_ANOMALY: 'SPATIAL_CLUSTER_ANOMALY',
  RATE_OF_CHANGE_ANOMALY: 'RATE_OF_CHANGE_ANOMALY',
  MULTI_SENSOR_ANOMALY: 'MULTI_SENSOR_ANOMALY',
  FORECAST_DEVIATION: 'FORECAST_DEVIATION',
});

export const SecondaryRiskLevel = Object.freeze({
  LOW: 'LOW',
  MODERATE: 'MODERATE',
  ELEVATED: 'ELEVATED',
  HIGH: 'HIGH',
  UNKNOWN: 'UNKNOWN',
});
